### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by sswebcoder** [sconts/kazam#20]
Kazam app can't start because has error when prepare config.

OS: Arch Linux
Stacktrace:

`/usr/bin/kazam:32: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/usr/bin/kazam:75: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
  dist = platform.linux_distribution()
Traceback (most recent call last):
  File "/usr/bin/kazam", line 146, in <module>
    from kazam.app import KazamApp
  File "/usr/lib/python3.7/site-packages/kazam/app.py", line 35, in <module>
    from kazam.backend.prefs import *
  File "/usr/lib/python3.7/site-packages/kazam/backend/prefs.py", line 478, in <module>
    prefs = Prefs()
  File "/usr/lib/python3.7/site-packages/kazam/backend/prefs.py", line 119, in __init__
    self.config = KazamConfig()
  File "/usr/lib/python3.7/site-packages/kazam/backend/config.py", line 76, in __init__
    ConfigParser.__init__(self, self.DEFAULTS[0]['keys'])
  File "/usr/lib/python3.7/configparser.py", line 638, in __init__
    self._read_defaults(defaults)
  File "/usr/lib/python3.7/configparser.py", line 1216, in _read_defaults
    self.read_dict({self.default_section: defaults})
  File "/usr/lib/python3.7/configparser.py", line 753, in read_dict
    self.set(section, key, value)
  File "/usr/lib/python3.7/site-packages/kazam/backend/config.py", line 127, in set
    self.add_section(section)
  File "/usr/lib/python3.7/configparser.py", line 1205, in add_section
    super().add_section(section)
  File "/usr/lib/python3.7/configparser.py", line 655, in add_section
    raise ValueError('Invalid section name: %r' % section)
ValueError: Invalid section name: 'DEFAULT'
`

I think what reason of crash is new version Configparser.

**Comment by ctrlcctrlv** [comment]
I fixed this in the AUR package (by forcing the use of Python 3.4's ConfigParser, taken from rewinding Git to an old release), you should use that in the mean time. If #21 is ever upstreamed I'll rewind my hack since I maintain `kazam` on AUR now
