### ISSUE TITLE
Ubuntu 20.04 error - no detection spikers

### ISSUE THREAD

**Issue by damufo** [sconts/kazam#39]
py-foi pc in ~
○ → kazam 
WARNING Kazam - Failed to correctly detect operating system.
/usr/lib/python3/dist-packages/kazam/app.py:145: Warning: value "((GtkIconSize) 32)" of type 'GtkIconSize' is invalid or out of range for property 'icon-size' of type 'GtkIconSize'
  self.builder.add_from_file(os.path.join(prefs.datadir, "ui", "kazam.ui"))

(kazam:190249): Gtk-WARNING **: 16:22:30.197: Can't set a parent on widget which has a parent

(kazam:190249): Gtk-WARNING **: 16:22:30.208: Can't set a parent on widget which has a parent
WARNING Prefs - Unable to find any audio devices.
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/kazam/frontend/preferences.py", line 256, in cb_audio2_changed
    pa_audio2_idx =  prefs.mic_sources[prefs.audio2_source][0]
IndexError: list index out of range

py-foi pc in ~
○ →

**Comment by campos20** [comment]
For those facing this same issue, until this repo gets updated again, you can

`sudo gedit /usr/lib/python3/dist-packages/kazam/pulseaudio/pulseaudio.py`

and replace its content with the PR content #40 that you can find [here](https://github.com/hzbd/kazam/blob/aca8dd4e2eb9caf676682933a06bc997decd5804/kazam/pulseaudio/pulseaudio.py).

**Comment by damufo** [comment]
Work fine for me.
Very thanks

**Comment by ralyodio** [comment]
somoene please fork and update

**Comment by LuigiMastroianni** [comment]
Work fine for me too!!!!! 
Very thanks thanks!!!!

**Comment by jglick** [comment]
Also tracked as: https://bugs.launchpad.net/ubuntu/+source/kazam/+bug/1876322

**Comment by bazzscript** [comment]
WARNING Kazam - Failed to correctly detect operating system.
Traceback (most recent call last):
  File "/usr/bin/kazam", line 148, in <module>
    from kazam.app import KazamApp
  File "/usr/lib/python3/dist-packages/kazam/app.py", line 35, in <module>
    from kazam.backend.prefs import *
  File "/usr/lib/python3/dist-packages/kazam/backend/prefs.py", line 478, in <module>
    prefs = Prefs()
  File "/usr/lib/python3/dist-packages/kazam/backend/prefs.py", line 121, in __init__
    self.read_config()
  File "/usr/lib/python3/dist-packages/kazam/backend/prefs.py", line 199, in read_config
    self.audio_source = int(self.config.get("main", "audio_source"))
  File "/usr/lib/python3/dist-packages/kazam/backend/config.py", line 106, in get
    self.set(section, key, default)
  File "/usr/lib/python3/dist-packages/kazam/backend/config.py", line 125, in set
    super().set(section, option, str(value))
  File "/usr/lib/python3.9/configparser.py", line 1204, in set
    super().set(section, option, value)
  File "/usr/lib/python3.9/configparser.py", line 902, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'mai
