### ISSUE TITLE
kazam fails to start

### ISSUE THREAD

**Issue by pradipcyb** [sconts/kazam#61]
The full traceback
`/usr/bin/kazam:32: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
    from gi.repository import Gtk
    Traceback (most recent call last):
      File "/usr/bin/kazam", line 146, in <module>
    from kazam.app import KazamApp
      File "/usr/lib/python3/dist-packages/kazam/app.py", line 35, in <module>
    from kazam.backend.prefs import *
      File "/usr/lib/python3/dist-packages/kazam/backend/prefs.py", line 26, in <module>
    from xdg.BaseDirectory import xdg_config_home
    ModuleNotFoundError: No module named 'xdg.BaseDirectory'
`
I tried installing python3-gi and python3-xdg but it didn't go away.

**Comment by niknah** [comment]
You might have another xdg folder somewhere else.

See where python is getting xdg from and if that folder has BaseDirectory.py

`PYTHONVERBOSE=2 python3`
`import xdg.BaseDirectory`

**Comment by andras-tim** [comment]
I have the same issue on _Ubuntu 20.04_.

The `/usr/local/lib/python3.8/dist-packages/xdg` package has overridden the `/usr/lib/python3/dist-packages/xdg` package...

I don't know how could it be (maybe `xdg` VS `pyxdg`?), but I renamed it and then things started to work:

``` sh
sudo mv /usr/local/lib/python3.8/dist-packages/xdg{,.orig}
```
