### ISSUE TITLE
Failed to correctly detect operating system.

### ISSUE THREAD

**Issue by bazzscript** [sconts/kazam#68]
WARNING Kazam - Failed to correctly detect operating system.
Traceback (most recent call last):
  File "/usr/bin/kazam", line 148, in <module>
    from kazam.app import KazamApp
  File "/usr/lib/python3/dist-packages/kazam/app.py", line 35, in <module>
    from kazam.backend.prefs import *
  File "/usr/lib/python3/dist-packages/kazam/backend/prefs.py", line 478, in <module>
    prefs = Prefs()
  File "/usr/lib/python3/dist-packages/kazam/backend/prefs.py", line 121, in __init__
    self.read_config()
  File "/usr/lib/python3/dist-packages/kazam/backend/prefs.py", line 199, in read_config
    self.audio_source = int(self.config.get("main", "audio_source"))
  File "/usr/lib/python3/dist-packages/kazam/backend/config.py", line 106, in get
    self.set(section, key, default)
  File "/usr/lib/python3/dist-packages/kazam/backend/config.py", line 125, in set
    super().set(section, option, str(value))
  File "/usr/lib/python3.9/configparser.py", line 1204, in set
    super().set(section, option, value)
  File "/usr/lib/python3.9/configparser.py", line 902, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'mai

**Comment by niknah** [comment]
That's the "warning" message.
The error message is...
configparser.NoSectionError: No section: 'mai

Maybe there's more and it was cut off.

Do you have a [main] section In the file... ~/.config/kazam/kazam.conf

Try removing/renaming that file and starting it again.

**Comment by bazzscript** [comment]
WARNING Kazam - Failed to correctly detect operating system.
Traceback (most recent call last):
  File "/usr/bin/kazam", line 148, in <module>
    from kazam.app import KazamApp
  File "/usr/lib/python3/dist-packages/kazam/app.py", line 35, in <module>
    from kazam.backend.prefs import *
  File "/usr/lib/python3/dist-packages/kazam/backend/prefs.py", line 478, in <module>
    prefs = Prefs()
  File "/usr/lib/python3/dist-packages/kazam/backend/prefs.py", line 121, in __init__
    self.read_config()
  File "/usr/lib/python3/dist-packages/kazam/backend/prefs.py", line 199, in read_config
    self.audio_source = int(self.config.get("main", "audio_source"))
  File "/usr/lib/python3/dist-packages/kazam/backend/config.py", line 106, in get
    self.set(section, key, default)
  File "/usr/lib/python3/dist-packages/kazam/backend/config.py", line 125, in set
    super().set(section, option, str(value))
  File "/usr/lib/python3.9/configparser.py", line 1204, in set
    super().set(section, option, value)
  File "/usr/lib/python3.9/configparser.py", line 902, in set
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'main'

**Comment by bazzscript** [comment]
this is the correct error message
its saying no section 'main'

**Comment by bazzscript** [comment]
how do i add main

**Comment by niknah** [comment]
In the file ~/.config/kazam/kazam.conf

There should be a [main] section

If you remove that file, it'll be recreated automatically.

**Comment by molecula451** [comment]
good to close, purging

`~/.config/kazam/kazam.conf`

seems to work
