### ISSUE TITLE
Crash when destination file system isn't available

### ISSUE THREAD

**Issue by MikePryadko** [sconts/kazam#70]
![image](https://user-images.githubusercontent.com/31248040/147548327-2417a282-169b-45b8-854b-deaae4e644e1.png)
---
system: `Ubuntu 20.04.3 (xubuntu)`
kazam: `1.5.4-0ubuntu7 [origin: LP-PPA-sylvain-pineau-kazam]`
error (from crash report):
```
 Traceback (most recent call last):
   File "/usr/lib/python3.8/shutil.py", line 791, in move
     os.rename(src, real_dst)
 FileNotFoundError: [Errno 2] No such file or directory: '/home/mike/Videos/kazam_azj9bgif.movie' -> '/media/ext_hdd/video/kazam__00000.mp4'
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "/usr/lib/python3/dist-packages/kazam/app.py", line 738, in cb_flush_done
     shutil.move(self.tempfile, fname)
   File "/usr/lib/python3.8/shutil.py", line 811, in move
     copy_function(src, real_dst)
   File "/usr/lib/python3.8/shutil.py", line 435, in copy2
     copyfile(src, dst, follow_symlinks=follow_symlinks)
   File "/usr/lib/python3.8/shutil.py", line 264, in copyfile
     with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
 FileNotFoundError: [Errno 2] No such file or directory: '/media/ext_hdd/video/kazam__00000.mp4'
```
### what is
specified in kazam's settings output directory was not mounted (i.e. `/media/` is empty)
### what should be
if output file can't be written kazam should interatively ask for new file path+name

###### \_\_\_thank you in advance___

**Comment by niknah** [comment]
Thanks for the suggestion,  you can try the commit above.
